-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.apps_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_name character varying NOT NULL,
  license_key character varying NOT NULL UNIQUE,
  supabase_url text NOT NULL,
  supabase_anon_key text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT apps_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ref_building_functions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_id uuid,
  function_name character varying NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT ref_building_functions_pkey PRIMARY KEY (id),
  CONSTRAINT ref_building_functions_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps_config(id),
  CONSTRAINT ref_building_functions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.ref_room_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_id uuid,
  category_name character varying NOT NULL,
  color_code character varying,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  icon_name character varying,
  marker_color text,
  CONSTRAINT ref_room_categories_pkey PRIMARY KEY (id),
  CONSTRAINT ref_room_categories_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps_config(id),
  CONSTRAINT ref_room_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.hospital_profile (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_id uuid,
  name character varying NOT NULL,
  address text,
  logo_url text,
  contact_center character varying,
  total_buildings integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hospital_profile_pkey PRIMARY KEY (id),
  CONSTRAINT hospital_profile_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps_config(id)
);
CREATE TABLE public.buildings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_id uuid,
  hospital_id uuid,
  building_name character varying NOT NULL,
  function_id uuid,
  total_floors integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  latitude double precision,
  longitude double precision,
  CONSTRAINT buildings_pkey PRIMARY KEY (id),
  CONSTRAINT buildings_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps_config(id),
  CONSTRAINT buildings_hospital_id_fkey FOREIGN KEY (hospital_id) REFERENCES public.hospital_profile(id),
  CONSTRAINT buildings_function_id_fkey FOREIGN KEY (function_id) REFERENCES public.ref_building_functions(id),
  CONSTRAINT buildings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.floors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_id uuid,
  building_id uuid,
  floor_number integer NOT NULL,
  floor_alias character varying,
  map_image_url text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT floors_pkey PRIMARY KEY (id),
  CONSTRAINT floors_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps_config(id),
  CONSTRAINT floors_building_id_fkey FOREIGN KEY (building_id) REFERENCES public.buildings(id),
  CONSTRAINT floors_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_id uuid,
  floor_id uuid,
  room_name character varying NOT NULL,
  category_id uuid,
  is_entry_gate boolean DEFAULT false,
  x_pos double precision DEFAULT 0.0,
  y_pos double precision DEFAULT 0.0,
  created_at timestamp with time zone DEFAULT now(),
  x_pos_max integer,
  y_pos_max integer,
  created_by uuid,
  CONSTRAINT rooms_pkey PRIMARY KEY (id),
  CONSTRAINT rooms_app_id_fkey FOREIGN KEY (app_id) REFERENCES public.apps_config(id),
  CONSTRAINT rooms_floor_id_fkey FOREIGN KEY (floor_id) REFERENCES public.floors(id),
  CONSTRAINT rooms_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.ref_room_categories(id),
  CONSTRAINT rooms_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  role text CHECK (role = ANY (ARRAY['operation'::text, 'management'::text, 'admin'::text, 'monitor'::text, 'control_room'::text])),
  rfid_tag text UNIQUE,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  address text,
  gender character,
  phone text,
  position_id uuid,
  avatar_url text,
  employee_id text,
  is_asset_initial boolean DEFAULT false,
  is_asset_inspection boolean DEFAULT false,
  is_stock_initial boolean DEFAULT false,
  is_stock_opname boolean DEFAULT false,
  is_flexible_roster boolean DEFAULT false,
  default_shift_id uuid,
  max_weekly_hours integer DEFAULT 40,
  max_daily_hours integer DEFAULT 8,
  preferred_shift_ids ARRAY DEFAULT '{}'::uuid[],
  wellbeing_risk_level text DEFAULT 'normal'::text,
  last_wellbeing_assessment timestamp with time zone,
  employee_nik character varying UNIQUE,
  unit_id uuid,
  unit_code character varying,
  join_date date,
  join_year integer,
  int_sequence integer DEFAULT 1,
  int_label character varying DEFAULT '1st'::character varying,
  current_situation character varying DEFAULT 'ACTIVE'::character varying,
  situation_notes text,
  situation_updated_at timestamp with time zone,
  rating_take_count integer DEFAULT 1,
  current_assignment text,
  assignment_destination text,
  assignment_started_at timestamp with time zone,
  assignment_eta timestamp with time zone,
  assignment_destination_lat double precision,
  assignment_destination_long double precision,
  is_stock_approval boolean DEFAULT false,
  is_approved boolean DEFAULT false,
  is_stock_admin boolean DEFAULT false,
  is_asset_admin boolean DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  is_people_input boolean DEFAULT false,
  can_register_people boolean DEFAULT false,
  can_bed_assignment boolean DEFAULT false,
  can_bed_unassignment boolean DEFAULT false,
  can_checkout_people boolean DEFAULT false,
  can_asset_initial boolean DEFAULT false,
  can_asset_inspection boolean DEFAULT false,
  can_stock_initial boolean DEFAULT false,
  can_asset_request boolean DEFAULT false,
  can_return_asset boolean DEFAULT false,
  can_stock_opname boolean DEFAULT false,
  can_stock_in boolean DEFAULT false,
  can_stock_placement boolean DEFAULT false,
  can_stock_request boolean DEFAULT false,
  can_stock_request_approval boolean DEFAULT false,
  can_stock_fulfillment boolean DEFAULT false,
  can_stock_write_off boolean DEFAULT false,
  can_stock_write_off_approval boolean DEFAULT false,
  can_building_reference boolean DEFAULT false,
  can_bins_reference boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_position_id_fkey FOREIGN KEY (position_id) REFERENCES public.ref_positions(id),
  CONSTRAINT profiles_default_shift_id_fkey FOREIGN KEY (default_shift_id) REFERENCES public.ref_shifts(id),
  CONSTRAINT profiles_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.employee_units(id)
);
CREATE TABLE public.ref_task_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_type_name text NOT NULL,
  icon_name text,
  color_code text,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ref_task_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type_id uuid NOT NULL,
  assignee_id uuid NOT NULL,
  object_name text NOT NULL,
  from_room_id uuid NOT NULL,
  to_room_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  priority text NOT NULL DEFAULT 'normal'::text,
  created_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_by uuid,
  task_outcome text,
  completion_notes text,
  app_id uuid,
  asset_id uuid,
  stock_id uuid,
  related_profile_id uuid,
  accepted_at timestamp with time zone,
  rejected_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  rejection_reason text,
  sla_minutes integer,
  estimated_duration_minutes integer,
  actual_duration_minutes integer,
  ai_generated boolean DEFAULT false,
  ai_priority_score numeric,
  ai_confidence_score numeric,
  ai_recommendation_reason text,
  fatigue_before numeric,
  fatigue_after numeric,
  wellbeing_impact_score numeric,
  workload_snapshot integer,
  requires_confirmation boolean DEFAULT false,
  requires_photo_proof boolean DEFAULT false,
  requires_qr_validation boolean DEFAULT false,
  proof_photo_url text,
  employee_feedback text,
  employee_rating integer,
  updated_at timestamp with time zone DEFAULT now(),
  completion_lat double precision,
  completion_long double precision,
  completion_address text,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_type_fkey FOREIGN KEY (type_id) REFERENCES public.ref_task_types(id),
  CONSTRAINT tasks_assignee_fkey FOREIGN KEY (assignee_id) REFERENCES public.profiles(id),
  CONSTRAINT tasks_from_room_fkey FOREIGN KEY (from_room_id) REFERENCES public.rooms(id),
  CONSTRAINT tasks_to_room_fkey FOREIGN KEY (to_room_id) REFERENCES public.rooms(id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT tasks_asset_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT tasks_related_profile_fkey FOREIGN KEY (related_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT tasks_stock_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id)
);
CREATE TABLE public.ref_shifts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shift_name character varying NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  app_id uuid,
  shift_code character varying,
  description text,
  is_cross_day boolean DEFAULT false,
  break_duration_minutes integer DEFAULT 60,
  tolerance_late_minutes integer DEFAULT 15,
  tolerance_early_leave_minutes integer DEFAULT 15,
  minimum_work_minutes integer DEFAULT 480,
  maximum_overtime_minutes integer DEFAULT 240,
  fatigue_weight numeric DEFAULT 1.00,
  risk_level text DEFAULT 'normal'::text,
  requires_medical_fit boolean DEFAULT false,
  requires_supervisor boolean DEFAULT false,
  requires_checkin_photo boolean DEFAULT false,
  requires_location_validation boolean DEFAULT true,
  ai_priority_weight numeric DEFAULT 1.00,
  wellbeing_monitoring_enabled boolean DEFAULT true,
  auto_assign_allowed boolean DEFAULT true,
  color_hex character varying DEFAULT '#2196F3'::character varying,
  icon_name character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ref_shifts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_id uuid,
  profile_id uuid NOT NULL,
  shift_id uuid,
  check_in timestamp with time zone DEFAULT now(),
  check_out timestamp with time zone,
  location_check_in uuid,
  status text NOT NULL DEFAULT 'present'::text,
  is_overtime boolean DEFAULT false,
  is_available boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  lat double precision,
  long double precision,
  address_at_check_in text,
  roster_id uuid,
  session_id uuid DEFAULT gen_random_uuid(),
  is_tracking_active boolean DEFAULT false,
  last_tracking_lat double precision,
  last_tracking_long double precision,
  last_tracking_address text,
  last_tracking_at timestamp with time zone,
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_profile_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT attendance_shift_fkey FOREIGN KEY (shift_id) REFERENCES public.ref_shifts(id),
  CONSTRAINT attendance_location_fkey FOREIGN KEY (location_check_in) REFERENCES public.rooms(id),
  CONSTRAINT attendance_roster_id_fkey FOREIGN KEY (roster_id) REFERENCES public.employee_shift_rosters(id)
);
CREATE TABLE public.ref_positions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  position_name text NOT NULL,
  description text,
  level smallint,
  color text,
  icon_name text,
  level_name text,
  CONSTRAINT ref_positions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ref_reports_category (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  description text,
  icon_name text,
  CONSTRAINT ref_reports_category_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tasks_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid NOT NULL,
  category_id uuid NOT NULL,
  reporter_id uuid NOT NULL,
  description text NOT NULL,
  urgency_level text NOT NULL DEFAULT 'normal'::text,
  at_room_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  file_url text,
  file_type text,
  CONSTRAINT tasks_reports_pkey PRIMARY KEY (id),
  CONSTRAINT tr_task_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT tr_category_fkey FOREIGN KEY (category_id) REFERENCES public.ref_reports_category(id),
  CONSTRAINT tr_reporter_fkey FOREIGN KEY (reporter_id) REFERENCES public.profiles(id),
  CONSTRAINT tr_room_fkey FOREIGN KEY (at_room_id) REFERENCES public.rooms(id)
);
CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['normal'::text, 'urgent'::text, 'emergency'::text])),
  target_building_id uuid,
  target_floor_id uuid,
  target_room_id uuid,
  target_position_id uuid,
  target_profile_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  target_role text,
  target_unit_id uuid,
  target_permission_asset text,
  target_permission_stock text,
  target_flexible_roster boolean,
  target_wellbeing_risk text,
  target_join_year_start integer,
  target_join_year_end integer,
  target_situation text,
  target_gender character,
  target_rating_take_count_min integer,
  target_rating_take_count_max integer,
  target_int_sequence_min integer,
  target_int_sequence_max integer,
  target_fatigue_score_min numeric,
  target_fatigue_score_max numeric,
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT ann_sender_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id),
  CONSTRAINT ann_building_fkey FOREIGN KEY (target_building_id) REFERENCES public.ref_building_functions(id),
  CONSTRAINT ann_floor_fkey FOREIGN KEY (target_floor_id) REFERENCES public.floors(id),
  CONSTRAINT ann_room_fkey FOREIGN KEY (target_room_id) REFERENCES public.rooms(id),
  CONSTRAINT ann_position_fkey FOREIGN KEY (target_position_id) REFERENCES public.ref_positions(id),
  CONSTRAINT ann_profile_fkey FOREIGN KEY (target_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT announcements_target_unit_id_fkey FOREIGN KEY (target_unit_id) REFERENCES public.employee_units(id)
);
CREATE TABLE public.ref_people_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_name character varying NOT NULL,
  marker_color character varying,
  created_at timestamp with time zone DEFAULT now(),
  is_insider boolean,
  CONSTRAINT ref_people_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.people (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_id uuid,
  rfid_tag_id character varying NOT NULL UNIQUE,
  full_name character varying NOT NULL,
  category_id uuid,
  foto_url text,
  is_male boolean NOT NULL DEFAULT true,
  is_child boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  last_detector_id uuid,
  last_room_id uuid,
  last_detected_at timestamp with time zone,
  last_movement_status text,
  updated_at timestamp with time zone DEFAULT now(),
  level_contaminated text,
  CONSTRAINT people_pkey PRIMARY KEY (id),
  CONSTRAINT people_last_detector_id_fkey FOREIGN KEY (last_detector_id) REFERENCES public.detectors(id),
  CONSTRAINT people_last_room_id_fkey FOREIGN KEY (last_room_id) REFERENCES public.rooms(id),
  CONSTRAINT people_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.ref_people_categories(id)
);
CREATE TABLE public.detectors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_id uuid,
  detector_code character varying NOT NULL UNIQUE,
  room_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT detectors_pkey PRIMARY KEY (id),
  CONSTRAINT detectors_room_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id)
);
CREATE TABLE public.people_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rfid_tag_id character varying NOT NULL,
  detector_id uuid NOT NULL,
  level_contaminated integer DEFAULT 0,
  movement_status character varying DEFAULT 'IN'::character varying,
  detected_at timestamp with time zone DEFAULT now(),
  CONSTRAINT people_movements_pkey PRIMARY KEY (id),
  CONSTRAINT pm_rfid_fkey FOREIGN KEY (rfid_tag_id) REFERENCES public.people(rfid_tag_id),
  CONSTRAINT pm_detector_fkey FOREIGN KEY (detector_id) REFERENCES public.detectors(id)
);
CREATE TABLE public.ref_asset_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type_name character varying NOT NULL,
  icon_name character varying,
  created_at timestamp with time zone DEFAULT now(),
  marker_color text,
  sub_category_id uuid,
  created_by uuid,
  CONSTRAINT ref_asset_types_pkey PRIMARY KEY (id),
  CONSTRAINT ref_asset_types_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT ref_asset_types_sub_category_id_fkey FOREIGN KEY (sub_category_id) REFERENCES public.ref_asset_sub_categories(id)
);
CREATE TABLE public.assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rfid_tag_id character varying NOT NULL UNIQUE,
  asset_name character varying NOT NULL,
  type_id uuid,
  foto_url text,
  status_condition character varying DEFAULT 'Good'::character varying,
  level_contaminated integer DEFAULT 0 CHECK (level_contaminated >= 0 AND level_contaminated <= 5),
  is_dangerous boolean DEFAULT false,
  handling_instruction text,
  maintenance_pattern character varying,
  inspection_day_of_month integer CHECK (inspection_day_of_month >= 1 AND inspection_day_of_month <= 31),
  last_inspection_at timestamp with time zone,
  next_inspection_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_detector_id uuid,
  last_room_id uuid,
  last_detected_at timestamp with time zone,
  last_movement_status text,
  description text,
  registered_by uuid,
  updated_by uuid,
  registered_at timestamp with time zone DEFAULT now(),
  last_used_by uuid,
  last_assigned_at timestamp with time zone,
  last_inspection_id uuid,
  last_inspection_result text,
  last_inspection_notes text,
  last_action_taken text,
  last_recommendation text,
  qrcode_url text,
  danger_level_id uuid,
  CONSTRAINT assets_pkey PRIMARY KEY (id),
  CONSTRAINT assets_last_inspection_id_fkey FOREIGN KEY (last_inspection_id) REFERENCES public.asset_inspections(id),
  CONSTRAINT assets_type_fkey FOREIGN KEY (type_id) REFERENCES public.ref_asset_types(id),
  CONSTRAINT assets_last_detector_id_fkey FOREIGN KEY (last_detector_id) REFERENCES public.detectors(id),
  CONSTRAINT assets_last_room_id_fkey FOREIGN KEY (last_room_id) REFERENCES public.rooms(id),
  CONSTRAINT assets_registered_by_fkey FOREIGN KEY (registered_by) REFERENCES public.profiles(id),
  CONSTRAINT assets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT assets_last_used_by_fkey FOREIGN KEY (last_used_by) REFERENCES public.profiles(id),
  CONSTRAINT assets_danger_level_id_fkey FOREIGN KEY (danger_level_id) REFERENCES public.ref_asset_danger_levels(id)
);
CREATE TABLE public.asset_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL,
  detector_id uuid NOT NULL,
  movement_status character varying DEFAULT 'IN'::character varying CHECK (movement_status::text = ANY (ARRAY['IN'::character varying, 'OUT'::character varying]::text[])),
  level_contaminated integer DEFAULT 0,
  detected_at timestamp with time zone DEFAULT now(),
  CONSTRAINT asset_movements_pkey PRIMARY KEY (id),
  CONSTRAINT asset_movements_asset_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT asset_movements_detector_fkey FOREIGN KEY (detector_id) REFERENCES public.detectors(id)
);
CREATE TABLE public.ref_asset_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_name character varying NOT NULL UNIQUE,
  icon_name character varying,
  marker_color text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT ref_asset_categories_pkey PRIMARY KEY (id),
  CONSTRAINT ref_asset_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.ref_asset_sub_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  sub_category_name character varying NOT NULL,
  icon_name character varying,
  marker_color text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT ref_asset_sub_categories_pkey PRIMARY KEY (id),
  CONSTRAINT ref_asset_sub_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.ref_asset_categories(id),
  CONSTRAINT ref_asset_sub_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.asset_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  released_at timestamp with time zone,
  assignment_status text DEFAULT 'active'::text CHECK (assignment_status = ANY (ARRAY['pending'::text, 'active'::text, 'rejected'::text, 'released'::text, 'transferred'::text, 'lost'::text, 'maintenance'::text])),
  notes text,
  created_by uuid,
  app_id uuid,
  assigned_by uuid,
  assignment_type text,
  handover_location_id uuid,
  return_location_id uuid,
  contamination_responsibility boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT asset_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_asset FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT fk_profile FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT fk_assigned_by FOREIGN KEY (assigned_by) REFERENCES public.profiles(id),
  CONSTRAINT fk_handover_location FOREIGN KEY (handover_location_id) REFERENCES public.rooms(id),
  CONSTRAINT fk_return_location FOREIGN KEY (return_location_id) REFERENCES public.rooms(id)
);
CREATE TABLE public.asset_inspections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL,
  inspected_by uuid NOT NULL,
  inspection_type text,
  inspection_result text,
  condition_status text,
  contamination_level integer,
  notes text,
  action_taken text,
  recommendation text,
  inspected_at timestamp with time zone DEFAULT now(),
  next_inspection_at timestamp with time zone,
  photo_url text,
  app_id uuid,
  task_id uuid,
  risk_score numeric,
  inspection_duration_minutes integer,
  proof_video_url text,
  ai_detected_issue text,
  ai_prediction text,
  ai_health_score numeric,
  ai_failure_probability numeric,
  fatigue_level numeric,
  requires_followup boolean DEFAULT false,
  followup_priority text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT asset_inspections_pkey PRIMARY KEY (id),
  CONSTRAINT fk_asset_inspection_asset FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT fk_asset_inspection_profile FOREIGN KEY (inspected_by) REFERENCES public.profiles(id),
  CONSTRAINT fk_asset_inspection_task FOREIGN KEY (task_id) REFERENCES public.tasks(id)
);
CREATE TABLE public.ref_stock_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type_name character varying NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  sub_category_id uuid,
  icon_name character varying,
  marker_color text,
  CONSTRAINT ref_stock_types_pkey PRIMARY KEY (id),
  CONSTRAINT ref_stock_types_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT ref_stock_types_sub_category_id_fkey FOREIGN KEY (sub_category_id) REFERENCES public.ref_stock_sub_categories(id)
);
CREATE TABLE public.stocks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stock_code character varying UNIQUE,
  stock_name character varying NOT NULL,
  stock_type_id uuid,
  unit character varying NOT NULL,
  minimum_stock numeric DEFAULT 0 CHECK (minimum_stock >= 0::numeric),
  current_stock numeric DEFAULT 0,
  photo_url text,
  last_opname_at timestamp with time zone,
  last_opname_by uuid,
  last_opname_note text,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  stock_condition character varying DEFAULT 'GOOD'::character varying,
  last_opname_stock numeric,
  last_purchase_at timestamp with time zone,
  last_purchase_by uuid,
  last_purchase_qty numeric,
  last_purchase_price numeric,
  last_usage_at timestamp with time zone,
  last_usage_by uuid,
  last_usage_qty numeric,
  storage_location_id uuid,
  batch_number character varying,
  description text,
  expiry_date timestamp without time zone,
  created_by uuid,
  stock_in_qty numeric DEFAULT 0,
  CONSTRAINT stocks_pkey PRIMARY KEY (id),
  CONSTRAINT stocks_last_purchase_by_fkey FOREIGN KEY (last_purchase_by) REFERENCES public.profiles(id),
  CONSTRAINT stocks_stock_type_id_fkey FOREIGN KEY (stock_type_id) REFERENCES public.ref_stock_types(id),
  CONSTRAINT stocks_last_opname_by_fkey FOREIGN KEY (last_opname_by) REFERENCES public.profiles(id),
  CONSTRAINT stocks_last_usage_by_fkey FOREIGN KEY (last_usage_by) REFERENCES public.profiles(id),
  CONSTRAINT stocks_storage_location_id_fkey FOREIGN KEY (storage_location_id) REFERENCES public.storage_locations(id),
  CONSTRAINT stocks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.stocks_opnames (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stock_id uuid NOT NULL,
  stock_before numeric DEFAULT 0,
  physical_stock numeric NOT NULL,
  adjustment_stock numeric DEFAULT 0,
  opname_note text,
  opname_by uuid,
  opname_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  bin_id uuid,
  stock_in_bins_id uuid,
  batch_number character varying,
  expiry_date date,
  system_quantity numeric,
  opname_type character varying DEFAULT 'PRODUCT'::character varying,
  CONSTRAINT stocks_opnames_pkey PRIMARY KEY (id),
  CONSTRAINT stocks_opnames_bin_id_fkey FOREIGN KEY (bin_id) REFERENCES public.stock_bins(id),
  CONSTRAINT stocks_opnames_stock_in_bins_id_fkey FOREIGN KEY (stock_in_bins_id) REFERENCES public.stock_in_bins(id),
  CONSTRAINT stocks_opnames_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id),
  CONSTRAINT stocks_opnames_opname_by_fkey FOREIGN KEY (opname_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.employee_shift_rosters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_id uuid,
  profile_id uuid NOT NULL,
  shift_id uuid NOT NULL,
  roster_date date NOT NULL,
  scheduled_start timestamp with time zone,
  scheduled_end timestamp with time zone,
  is_day_off boolean DEFAULT false,
  is_overtime_planned boolean DEFAULT false,
  is_emergency_shift boolean DEFAULT false,
  is_on_call boolean DEFAULT false,
  ai_generated boolean DEFAULT false,
  ai_confidence_score numeric,
  ai_reason text,
  predicted_fatigue_score numeric,
  predicted_workload_score numeric,
  predicted_stress_score numeric,
  wellbeing_risk_level text,
  approval_status text DEFAULT 'pending'::text,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  actual_check_in timestamp with time zone,
  actual_check_out timestamp with time zone,
  attendance_status text DEFAULT 'scheduled'::text,
  total_work_minutes integer,
  overtime_minutes integer DEFAULT 0,
  lateness_minutes integer DEFAULT 0,
  early_leave_minutes integer DEFAULT 0,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  location_name character varying,
  location_room_id uuid,
  required_equipment ARRAY DEFAULT '{}'::text[],
  special_instructions text,
  leave_request_id uuid,
  qualification_required ARRAY DEFAULT '{}'::uuid[],
  min_score_required numeric,
  CONSTRAINT employee_shift_rosters_pkey PRIMARY KEY (id),
  CONSTRAINT fk_employee_shift_profile FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_employee_shift_shift FOREIGN KEY (shift_id) REFERENCES public.ref_shifts(id),
  CONSTRAINT fk_employee_shift_approved_by FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT fk_employee_shift_created_by FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT employee_shift_rosters_location_room_id_fkey FOREIGN KEY (location_room_id) REFERENCES public.rooms(id),
  CONSTRAINT employee_shift_rosters_leave_request_id_fkey FOREIGN KEY (leave_request_id) REFERENCES public.employee_leave_requests(id)
);
CREATE TABLE public.employee_wellbeing_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  app_id uuid,
  profile_id uuid NOT NULL,
  log_date date NOT NULL,
  fatigue_score numeric,
  stress_score numeric,
  mood_score numeric,
  energy_score numeric,
  sleep_hours numeric,
  self_report text,
  ai_burnout_risk numeric,
  ai_recommendation text,
  requires_attention boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_wellbeing_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_wellbeing_profile FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.ref_incident_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  icon character varying,
  color character varying,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ref_incident_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.incidents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  reported_by uuid NOT NULL,
  room_id uuid,
  title character varying NOT NULL,
  description text NOT NULL,
  occurred_at timestamp with time zone NOT NULL,
  location_text text,
  status character varying NOT NULL DEFAULT 'reported'::character varying,
  photo_urls jsonb,
  voice_note_url text,
  ai_tags jsonb,
  ai_analysis jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  severity character varying DEFAULT 'MEDIUM'::character varying CHECK (severity::text = ANY (ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying]::text[])),
  assigned_to uuid,
  resolved_at timestamp with time zone,
  resolution_note text,
  lat double precision,
  long double precision,
  address text,
  action_taken text,
  action_taken_at timestamp with time zone,
  action_taken_by uuid,
  action_task_ids ARRAY,
  action_taken_model text,
  action_announcement_ids ARRAY,
  CONSTRAINT incidents_pkey PRIMARY KEY (id),
  CONSTRAINT incidents_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.ref_incident_categories(id),
  CONSTRAINT incidents_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.profiles(id),
  CONSTRAINT incidents_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT incidents_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT incidents_action_taken_by_fkey FOREIGN KEY (action_taken_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.storage_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  location_code character varying NOT NULL UNIQUE,
  location_name character varying NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT storage_locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stock_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stock_id uuid NOT NULL,
  transaction_type character varying NOT NULL,
  qty numeric NOT NULL,
  stock_before numeric NOT NULL,
  stock_after numeric NOT NULL,
  transaction_note text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT stock_transactions_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id),
  CONSTRAINT stock_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.employee_units (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  unit_code character varying NOT NULL UNIQUE,
  unit_name character varying NOT NULL,
  parent_unit_id uuid,
  unit_level integer DEFAULT 1,
  head_of_unit_id uuid,
  shift_required boolean DEFAULT true,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  level smallint,
  CONSTRAINT employee_units_pkey PRIMARY KEY (id),
  CONSTRAINT employee_units_parent_unit_id_fkey FOREIGN KEY (parent_unit_id) REFERENCES public.employee_units(id),
  CONSTRAINT employee_units_head_of_unit_id_fkey FOREIGN KEY (head_of_unit_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.employee_qualifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  qualification_code character varying NOT NULL UNIQUE,
  qualification_name character varying NOT NULL,
  category character varying,
  validity_period_months integer,
  requires_renewal boolean DEFAULT true,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_qualifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.employee_qualification_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  qualification_id uuid NOT NULL,
  acquired_date date NOT NULL,
  expiry_date date,
  certificate_number character varying,
  score numeric,
  is_active boolean DEFAULT true,
  verified_by uuid,
  verified_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_qualification_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT employee_qualification_assignments_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT employee_qualification_assignments_qualification_id_fkey FOREIGN KEY (qualification_id) REFERENCES public.employee_qualifications(id),
  CONSTRAINT employee_qualification_assignments_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.leave_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  leave_code character varying NOT NULL UNIQUE,
  leave_name character varying NOT NULL,
  max_days_per_year integer,
  paid_leave boolean DEFAULT true,
  requires_document boolean DEFAULT false,
  requires_medical_certificate boolean DEFAULT false,
  color character varying DEFAULT '#FF9800'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leave_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.employee_leave_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  total_days integer NOT NULL,
  reason text,
  document_url text,
  approval_status character varying DEFAULT 'pending'::character varying,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT employee_leave_requests_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT employee_leave_requests_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id),
  CONSTRAINT employee_leave_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT employee_leave_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.scoring_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_code character varying NOT NULL UNIQUE,
  category_name character varying NOT NULL,
  weight numeric DEFAULT 1.00,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scoring_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.employee_scoring (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  scoring_category_id uuid NOT NULL,
  score numeric NOT NULL DEFAULT 0,
  max_score numeric NOT NULL DEFAULT 100,
  period_start date NOT NULL,
  period_end date NOT NULL,
  notes text,
  calculated_at timestamp with time zone DEFAULT now(),
  calculated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employee_scoring_pkey PRIMARY KEY (id),
  CONSTRAINT employee_scoring_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT employee_scoring_scoring_category_id_fkey FOREIGN KEY (scoring_category_id) REFERENCES public.scoring_categories(id),
  CONSTRAINT employee_scoring_calculated_by_fkey FOREIGN KEY (calculated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.duty_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  attendance_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  note_text text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT duty_notes_pkey PRIMARY KEY (id),
  CONSTRAINT duty_notes_attendance_id_fkey FOREIGN KEY (attendance_id) REFERENCES public.attendance(id),
  CONSTRAINT duty_notes_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.employee_location_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  session_id uuid NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  accuracy double precision,
  speed double precision,
  altitude double precision,
  is_moving boolean DEFAULT false,
  recorded_at timestamp with time zone DEFAULT now(),
  device_info jsonb,
  CONSTRAINT employee_location_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT employee_location_tracking_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_location_profile FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.stock_warehouses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  address text,
  manager_id uuid,
  is_active boolean DEFAULT true,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  floor_id uuid,
  created_by uuid,
  CONSTRAINT stock_warehouses_pkey PRIMARY KEY (id),
  CONSTRAINT stock_warehouses_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.profiles(id),
  CONSTRAINT stock_warehouses_floor_id_fkey FOREIGN KEY (floor_id) REFERENCES public.floors(id),
  CONSTRAINT stock_warehouses_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.stock_zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  warehouse_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  zone_type character varying DEFAULT 'NORMAL'::character varying,
  temperature_min numeric,
  temperature_max numeric,
  humidity_min numeric,
  humidity_max numeric,
  is_restricted boolean DEFAULT false,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  room_id uuid,
  created_by uuid,
  CONSTRAINT stock_zones_pkey PRIMARY KEY (id),
  CONSTRAINT stock_zones_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.stock_warehouses(id),
  CONSTRAINT stock_zones_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT stock_zones_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.stock_racks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  zone_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying,
  capacity_kg numeric,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT stock_racks_pkey PRIMARY KEY (id),
  CONSTRAINT stock_racks_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.stock_zones(id),
  CONSTRAINT stock_racks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.stock_shelves (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rack_id uuid NOT NULL,
  level_number integer NOT NULL,
  code character varying NOT NULL,
  max_height_cm numeric,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT stock_shelves_pkey PRIMARY KEY (id),
  CONSTRAINT stock_shelves_rack_id_fkey FOREIGN KEY (rack_id) REFERENCES public.stock_racks(id),
  CONSTRAINT stock_shelves_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.stock_bins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shelf_id uuid NOT NULL,
  code character varying NOT NULL,
  barcode character varying UNIQUE,
  position_x integer,
  position_y integer,
  max_quantity numeric,
  current_quantity numeric DEFAULT 0,
  current_product_id uuid,
  is_active boolean DEFAULT true,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  qrcode_url text,
  asset_id uuid,
  CONSTRAINT stock_bins_pkey PRIMARY KEY (id),
  CONSTRAINT stock_bins_shelf_id_fkey FOREIGN KEY (shelf_id) REFERENCES public.stock_shelves(id),
  CONSTRAINT stock_bins_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT stock_bins_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id)
);
CREATE TABLE public.stock_in_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entry_number character varying NOT NULL UNIQUE,
  stock_id uuid NOT NULL,
  quantity numeric NOT NULL,
  batch_number character varying NOT NULL,
  expiry_date date NOT NULL,
  source_type character varying NOT NULL CHECK (source_type::text = ANY (ARRAY['PURCHASE'::character varying, 'RETURN'::character varying, 'DONATION'::character varying, 'TRANSFER'::character varying]::text[])),
  source_id character varying,
  entry_date timestamp with time zone DEFAULT now(),
  received_bin_id uuid,
  current_bin_id uuid,
  received_by uuid,
  returned_by uuid,
  returned_from_unit character varying,
  return_reason character varying,
  put_away_by uuid,
  verified_by uuid,
  verified_at timestamp with time zone,
  risk_level character varying DEFAULT 'NORMAL'::character varying,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_in_entries_pkey PRIMARY KEY (id),
  CONSTRAINT stock_in_entries_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id),
  CONSTRAINT stock_in_entries_received_bin_id_fkey FOREIGN KEY (received_bin_id) REFERENCES public.stock_bins(id),
  CONSTRAINT stock_in_entries_current_bin_id_fkey FOREIGN KEY (current_bin_id) REFERENCES public.stock_bins(id),
  CONSTRAINT stock_in_entries_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.profiles(id),
  CONSTRAINT stock_in_entries_returned_by_fkey FOREIGN KEY (returned_by) REFERENCES public.profiles(id),
  CONSTRAINT stock_in_entries_put_away_by_fkey FOREIGN KEY (put_away_by) REFERENCES public.profiles(id),
  CONSTRAINT stock_in_entries_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.stock_in (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  receipt_number character varying NOT NULL UNIQUE,
  stock_id uuid NOT NULL,
  quantity numeric NOT NULL,
  batch_number character varying NOT NULL,
  expiry_date date NOT NULL,
  source_type character varying NOT NULL DEFAULT 'PURCHASE'::character varying,
  source_reference character varying,
  returned_from_unit character varying,
  return_reason character varying,
  received_by uuid,
  received_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'RECEIVED'::character varying,
  verified_by uuid,
  verified_at timestamp with time zone,
  risk_level character varying DEFAULT 'NORMAL'::character varying,
  notes text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_in_pkey PRIMARY KEY (id),
  CONSTRAINT stock_in_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id),
  CONSTRAINT stock_in_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.profiles(id),
  CONSTRAINT stock_in_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.stock_in_bins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bin_id uuid NOT NULL,
  stock_id uuid NOT NULL,
  batch_number character varying NOT NULL,
  expiry_date date NOT NULL,
  quantity numeric NOT NULL CHECK (quantity >= 0::numeric),
  stock_in_id uuid,
  put_away_by uuid,
  put_away_at timestamp with time zone DEFAULT now(),
  scanned_bin_barcode character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_in_bins_pkey PRIMARY KEY (id),
  CONSTRAINT stock_in_bins_bin_id_fkey FOREIGN KEY (bin_id) REFERENCES public.stock_bins(id),
  CONSTRAINT stock_in_bins_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id),
  CONSTRAINT stock_in_bins_stock_in_id_fkey FOREIGN KEY (stock_in_id) REFERENCES public.stock_in(id),
  CONSTRAINT stock_in_bins_put_away_by_fkey FOREIGN KEY (put_away_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.stock_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_number character varying NOT NULL UNIQUE,
  requester_id uuid NOT NULL,
  requester_name character varying,
  room_id uuid,
  purpose character varying,
  request_date timestamp with time zone DEFAULT now(),
  notes text,
  requested_stock_id uuid NOT NULL,
  requested_stock_name character varying,
  requested_quantity numeric NOT NULL CHECK (requested_quantity > 0::numeric),
  requested_unit character varying,
  requested_batch character varying,
  approved_by uuid,
  approved_date timestamp with time zone,
  approved_quantity numeric,
  approved_stock_id uuid,
  approved_stock_name character varying,
  approval_notes text,
  status character varying DEFAULT 'PENDING'::character varying,
  fulfilled_quantity numeric DEFAULT 0 CHECK (fulfilled_quantity >= 0::numeric),
  rejected_by uuid,
  rejected_at timestamp with time zone,
  rejection_reason text,
  rejection_type character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_requests_pkey PRIMARY KEY (id),
  CONSTRAINT stock_requests_requester_id_fkey FOREIGN KEY (requester_id) REFERENCES public.profiles(id),
  CONSTRAINT stock_requests_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT stock_requests_requested_stock_id_fkey FOREIGN KEY (requested_stock_id) REFERENCES public.stocks(id),
  CONSTRAINT stock_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT stock_requests_approved_stock_id_fkey FOREIGN KEY (approved_stock_id) REFERENCES public.stocks(id),
  CONSTRAINT stock_requests_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.stock_request_fulfillments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  stock_request_id uuid NOT NULL,
  stock_in_bins_id uuid NOT NULL,
  bin_id uuid NOT NULL,
  stock_id uuid NOT NULL,
  batch_number character varying NOT NULL,
  expiry_date date NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  taken_by uuid NOT NULL,
  taken_at timestamp with time zone DEFAULT now(),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_request_fulfillments_pkey PRIMARY KEY (id),
  CONSTRAINT stock_request_fulfillments_taken_by_fkey FOREIGN KEY (taken_by) REFERENCES public.profiles(id),
  CONSTRAINT stock_request_fulfillments_stock_request_id_fkey FOREIGN KEY (stock_request_id) REFERENCES public.stock_requests(id),
  CONSTRAINT stock_request_fulfillments_stock_in_bins_id_fkey FOREIGN KEY (stock_in_bins_id) REFERENCES public.stock_in_bins(id),
  CONSTRAINT stock_request_fulfillments_bin_id_fkey FOREIGN KEY (bin_id) REFERENCES public.stock_bins(id),
  CONSTRAINT stock_request_fulfillments_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id)
);
CREATE TABLE public.stock_write_offs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  write_off_number character varying NOT NULL UNIQUE,
  stock_in_bins_id uuid NOT NULL,
  bin_id uuid NOT NULL,
  stock_id uuid NOT NULL,
  batch_number character varying NOT NULL,
  expiry_date date NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  unit character varying,
  reason character varying NOT NULL,
  reason_note text,
  requested_by uuid,
  requested_at timestamp with time zone DEFAULT now(),
  status character varying DEFAULT 'DRAFT'::character varying CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'APPROVED'::character varying]::text[])),
  photo_url text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_write_offs_pkey PRIMARY KEY (id),
  CONSTRAINT stock_write_offs_stock_in_bins_id_fkey FOREIGN KEY (stock_in_bins_id) REFERENCES public.stock_in_bins(id),
  CONSTRAINT stock_write_offs_bin_id_fkey FOREIGN KEY (bin_id) REFERENCES public.stock_bins(id),
  CONSTRAINT stock_write_offs_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id),
  CONSTRAINT stock_write_offs_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.stock_mutations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mutation_number character varying NOT NULL UNIQUE,
  stock_in_bins_id uuid NOT NULL,
  bin_id_asal uuid NOT NULL,
  bin_id_tujuan uuid NOT NULL,
  stock_id uuid NOT NULL,
  batch_number character varying NOT NULL,
  expiry_date date NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  unit character varying,
  moved_by uuid NOT NULL,
  moved_at timestamp with time zone DEFAULT now(),
  received_by uuid,
  received_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_mutations_pkey PRIMARY KEY (id),
  CONSTRAINT stock_mutations_stock_in_bins_id_fkey FOREIGN KEY (stock_in_bins_id) REFERENCES public.stock_in_bins(id),
  CONSTRAINT stock_mutations_bin_id_asal_fkey FOREIGN KEY (bin_id_asal) REFERENCES public.stock_bins(id),
  CONSTRAINT stock_mutations_bin_id_tujuan_fkey FOREIGN KEY (bin_id_tujuan) REFERENCES public.stock_bins(id),
  CONSTRAINT stock_mutations_stock_id_fkey FOREIGN KEY (stock_id) REFERENCES public.stocks(id),
  CONSTRAINT stock_mutations_moved_by_fkey FOREIGN KEY (moved_by) REFERENCES public.profiles(id),
  CONSTRAINT stock_mutations_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.ref_stock_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_name character varying NOT NULL UNIQUE,
  icon_name character varying,
  marker_color text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT ref_stock_categories_pkey PRIMARY KEY (id),
  CONSTRAINT ref_stock_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.ref_stock_sub_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  sub_category_name character varying NOT NULL,
  icon_name character varying,
  marker_color text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT ref_stock_sub_categories_pkey PRIMARY KEY (id),
  CONSTRAINT ref_stock_sub_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT ref_stock_sub_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.ref_stock_categories(id)
);
CREATE TABLE public.licenses (
  license_key character varying NOT NULL,
  is_active boolean DEFAULT true,
  client_name character varying,
  production_supabase_url text NOT NULL,
  production_anon_key text NOT NULL,
  gemini_api_key text,
  expiry_date date,
  created_at timestamp with time zone DEFAULT now(),
  package character varying DEFAULT 'basic'::character varying,
  CONSTRAINT licenses_pkey PRIMARY KEY (license_key)
);
CREATE TABLE public.todos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  duration_minutes integer,
  target_unit_id uuid,
  target_position_id uuid,
  target_shift_id uuid,
  todo_date date NOT NULL,
  start_time time without time zone,
  end_time time without time zone,
  source_type text DEFAULT 'admin_input'::text,
  source_id text,
  source_table text,
  source_data jsonb,
  is_active boolean DEFAULT true,
  expired_at timestamp with time zone,
  display_order integer DEFAULT 0,
  is_mandatory boolean DEFAULT true,
  priority text DEFAULT 'normal'::text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT todos_pkey PRIMARY KEY (id),
  CONSTRAINT fk_todos_target_unit FOREIGN KEY (target_unit_id) REFERENCES public.employee_units(id),
  CONSTRAINT fk_todos_target_position FOREIGN KEY (target_position_id) REFERENCES public.ref_positions(id),
  CONSTRAINT fk_todos_target_shift FOREIGN KEY (target_shift_id) REFERENCES public.ref_shifts(id),
  CONSTRAINT fk_todos_created_by FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.ref_asset_danger_levels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  level_code character varying NOT NULL UNIQUE,
  level_name character varying NOT NULL,
  risk_description text,
  protection_required text,
  handling_instruction text,
  color_hex character varying DEFAULT '#F59E0B'::character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ref_asset_danger_levels_pkey PRIMARY KEY (id)
);
CREATE TABLE public.beds (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  room_id uuid,
  bed_number character varying,
  asset_id uuid,
  status character varying DEFAULT 'EMPTY'::character varying,
  admitted_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT beds_pkey PRIMARY KEY (id),
  CONSTRAINT beds_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id),
  CONSTRAINT beds_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT beds_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.beds_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bed_id uuid NOT NULL,
  people_id uuid NOT NULL,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  predicted_until timestamp with time zone,
  discharged_at timestamp with time zone,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT beds_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT beds_assignments_bed_id_fkey FOREIGN KEY (bed_id) REFERENCES public.beds(id),
  CONSTRAINT beds_assignments_people_id_fkey FOREIGN KEY (people_id) REFERENCES public.people(id),
  CONSTRAINT beds_assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.testimonials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hospital_name text NOT NULL,
  user_name text,
  content text NOT NULL,
  rating integer DEFAULT 5,
  picture_url text,
  avatar_url text,
  is_published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT testimonials_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pricing_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  price_monthly integer,
  price_yearly integer,
  features jsonb,
  cta_text text,
  icon_name text,
  color_hex text,
  is_popular boolean DEFAULT false,
  is_active boolean DEFAULT true,
  CONSTRAINT pricing_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.features (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  menu_name text NOT NULL,
  description text NOT NULL,
  picture_url text,
  level integer DEFAULT 1,
  details jsonb,
  package_uuids ARRAY,
  icon_name text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  module_id uuid,
  display_order integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT features_pkey PRIMARY KEY (id),
  CONSTRAINT features_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.modules(id)
);
CREATE TABLE public.trusted_hospitals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  logo_url text NOT NULL,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trusted_hospitals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contact_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL,
  title text NOT NULL,
  description text,
  address text,
  whatsapp text,
  email text,
  contact_for text,
  logo_url text,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_info_pkey PRIMARY KEY (id)
);
CREATE TABLE public.head_office (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  address text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT head_office_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contact_note (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_note_pkey PRIMARY KEY (id)
);
CREATE TABLE public.packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  price_monthly numeric,
  price_yearly numeric,
  is_popular boolean DEFAULT false,
  features ARRAY DEFAULT '{}'::text[],
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  price_monthly_idr bigint,
  price_yearly_idr bigint,
  currency text DEFAULT 'IDR'::text,
  CONSTRAINT packages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.modules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_id uuid,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  icon_name text,
  display_order integer DEFAULT 0,
  is_coming boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT modules_pkey PRIMARY KEY (id),
  CONSTRAINT modules_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_number text NOT NULL UNIQUE,
  session_id text,
  user_id uuid,
  user_name text NOT NULL,
  user_email text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  status text DEFAULT 'open'::text,
  is_read_admin boolean DEFAULT false,
  is_read_user boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.support_replies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid,
  user_name text NOT NULL,
  user_role text DEFAULT 'user'::text,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_replies_pkey PRIMARY KEY (id),
  CONSTRAINT support_replies_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id)
);
CREATE TABLE public.downloads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  title_id text NOT NULL,
  description text,
  description_id text,
  icon_name text NOT NULL,
  file_url text NOT NULL,
  file_size text,
  version text,
  platform text,
  allowed_roles ARRAY DEFAULT '{}'::text[],
  download_count integer DEFAULT 0,
  display_order integer DEFAULT 0 UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT downloads_pkey PRIMARY KEY (id)
);